#!/usr/bin/env bash
# Displays information about subdomains.

# Uncomment for debugging purposes.
#set -x
# Function to query DNS information

domain="$1"
sub="$2"

query_dns() {

    info="$(dig "$sub.$domain" | grep -A1 'ANSWER SECTION:' | awk 'NR==2')"

    if [ -n "$info" ]; then
        # Extract IP address
      	ip=$(echo "$info" | awk '{print $5}')
        # Query DNS directly for record type
        record=$(echo "$info" | awk '{print $4}')

        echo "The subdomain $sub is a $record record and points to $ip"
    else
        echo "No information found for the subdomain $sub"
    fi
}

# Main script
if [ $# -eq 1 ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")

    for sub in "${subdomains[@]}"; do
        query_dns "$1" "$sub"
    done
elif [ $# -eq 2 ]; then
    query_dns "$1" "$2"
else
    echo "Usage: $0 <domain> [subdomain]"
fi
